name: Unity Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: MOTHERSHIP

    strategy:
      matrix:
        targetPlatform:
          - StandaloneWindows64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: |
            "Ruin The Runner/Library"
            "Ruin The Runner/Build"
          key: ${{ runner.os }}-unity-library-${{ matrix.targetPlatform }}-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-unity-library-${{ matrix.targetPlatform }}-

      - name: Set up Unity
        uses: game-ci/unity-builder@v4.2.3
        with:
          unityVersion: auto
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: "Ruin The Runner"
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Build project
        uses: game-ci/unity-builder@v4.2.3
        with:
          unityVersion: auto
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: "Ruin The Runner"
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: "Ruin The Runner/build"
