name: Unity Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - StandaloneOSX
          - StandaloneLinux64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2023.1.0f1
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        with:
          unityLicense: ${{ secrets.UNITY_LICENSE }}

      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2023.1.0f1
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build

      - name: Deactivate Unity License
        if: always()
        uses: game-ci/unity-return-license@v2
        with:
          unityLicense: ${{ secrets.UNITY_LICENSE }}
